ZZZ_system_chrome:
  executable: google-chrome
  urls:
    google_meet:
    - domain: meet.google.com
ZZZ_system_firefox:
  executable: firefox
  urls:
    ext_container:
    - scheme: ext+container
ZZZZ_default:
  executable: firefox